### PR TITLE
MQTT pattern matching for multi level wildcard

### LINKED ISSUE #11: MQTT pattern matching fails for multi level wildcard #
In the actual implementation, given 
`Building/{room}/#`  as the MQTT pattern.

The following topic should match it:
`building/4`
`building/4/temperature`

But the first one is not matching.

According to the [MQTT 3.1.1 topic specifications](http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/csprd02/mqtt-v3.1.1-csprd02.html#_Toc385349843:~:text=%C2%B7%C2%A0%C2%A0%C2%A0%C2%A0%C2%A0%C2%A0%C2%A0%C2%A0%20%E2%80%9Csport/%23%E2%80%9D%20also,receive%20every%20Application%20Message), if a client subscribes to `building/#`, the same clients should receive messages from `building/4`, `building/4/something`, `building` and other that applies.

### PR DESCRIPTION
**Pull request by antonio-pedro99**
This fixes #11

### CODE REVIEW

File: src/main/java/io/strimzi/kafka/bridge/mqtt/mapper/MqttKafkaMapper.java [hunk 1]
```diff
@@ -118,6 +118,9 @@ private void buildRegex() {
                 } else if (part.equals(MQTT_TOPIC_SINGLE_LEVEL_WILDCARD_CHARACTER)) {
                     ruleRegex.append(SINGLE_LEVEL_WILDCARD_REGEX);
                 } else if (part.equals(MQTT_TOPIC_MULTI_LEVEL_WILDCARD_CHARACTER)) {
+                    if (ruleRegex.length() > 1) {
+                        ruleRegex.deleteCharAt(ruleRegex.length() - 1);
```
Comment (antonio-pedro99) [inline src/main/java/io/strimzi/kafka/bridge/mqtt/mapper/MqttKafkaMapper.java:122]: Remove the last `/` before appending `.*` to the regex expression. 
If the pattern is `{house}/#`, the final regex will be `(?<house>[^/]+).*` 
and now `my_house/floor`, `first_house/temperature`, and `my_house` will match.

I have also tried using regex `lookaround`, but was not successful.

**Review by ppatierno — APPROVED** [review]
LGTM

**Review by kyguy — APPROVED** [review]
